### ISSUE TITLE
Provide a reference test suite for implementations to use

### ISSUE THREAD

**Issue by mperham** [evanw/thumbhash#12]
I'd like to work on a Ruby version but this repo has no easy way for me to verify my implementation. Looks like there is already a lot of demo image data on the demo website which could be used as part of an automated test suite.

**Comment by evanw** [comment]
The images and hashes on the demo website are a good set of tests. If you can render appropriate-looking images with those hashes then your code should be working.

Someone asked for a similar thing for BlurHash too: https://github.com/woltapp/blurhash/issues/38. I also agree with the response there. These things are meant to be a very loose very blurry representation of the image, so exact accuracy isn't the goal. It doesn't matter if you end up a few bits off due to e.g. using doubles vs. floats. So I don't think an automated test suite is the right approach here.

**Comment by mperham** [comment]
Fair enough.
